# Generated by Django 5.2.11 on 2026-02-08 09:06

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('raw_text', models.TextField()),
                ('original_file', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/')),
                ('file_type', models.CharField(default='md', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractionSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('schema_definition', models.JSONField(default=dict, help_text='Internal field definition format used by the visual builder.')),
                ('llm_provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('google', 'Google')], default='openai', max_length=50)),
                ('llm_model', models.CharField(default='gpt-4o', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Extraction Schema',
                'verbose_name_plural': 'Extraction Schemas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='pending', max_length=20)),
                ('result_data', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=10)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='documents.document')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='documents.extractionschema')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['result_data'], name='result_data_gin_idx')],
            },
        ),
    ]
